In [3]:
import pandas as pd
import pyarrow.parquet as pq
from IPython.display import display

parquet_path = "DeepScaler/Qwen2d5_math_7b/train_800.success_rate_k8.right.parquet"

In [4]:
# 1. 读取数据
df = pd.read_parquet(parquet_path)

# 2. 查看总数据量
print(f"=== 总数据量 ===")
print(f"共 {len(df)} 条数据\n")

=== 总数据量 ===
共 741 条数据

In [5]:
# 3. 查看字段列表
print(f"=== 字段列表 ({len(df.columns)} 个) ===")
print(df.columns.tolist(), "\n")

=== 字段列表 (27 个) ===
['question', 'solution', 'prompt', 'id', 'data_source', 'parsed_output', 'solution_breakdown_parts', 'model_answer', 'reward_model', 'knowledge_components_parts', 'ability', 'planning_skeleton_parts', 'model_think', 'extra_info', 'accuracy', 'solution_breakdown_cot_answer', 'solution_breakdown_parts_count', 'solution_breakdown_reward', 'qwen_original_row_index', 'source_row_index', 'difficulty_bucket', 'success_rate_at_k', 'success_count_at_k', 'rollout_reward_list', 'qwen_expert_trajectory', 'qwen_expert_trajectory_token_count', 'qwen_expert_trajectory_math_verify_score']

In [6]:
# 4. 查看第一条示例数据 (转换为字典方便打印)
print(f"=== 第 1 条数据示例 ===")
first_row = df.iloc[0].to_dict()
for key, value in first_row.items():
    print(f"[{key}]: {value}")

=== 第 1 条数据示例 ===
[question]: A committee of 5 is to be chosen from a group of 9 people. How many ways can it be chosen, if Bill and Karl must serve together or not at all, and Alice and Jane refuse to serve with each other?
[solution]: If Bill and Karl are on the committee, there are $\binom{7}{3}=35$ ways for the other group members to be chosen. However, if Alice and Jane are on the committee with Bill and Karl, there are $\binom{5}{1}=5$ ways for the last member to be chosen, yielding 5 unacceptable committees. If Bill and Karl are not on the committee, there are $\binom{7}{5}=21$ ways for the 5 members to be chosen, but again if Alice and Jane were to be on the committee, there would be $\binom{5}{3}=10$ ways to choose the other three members, yielding 10 more unacceptable committees. So, we obtain $(35-5)+(21-10)=41$ ways the committee can be chosen.
[prompt]: [{'content': 'Please reason step by step, and put your final answer within \\boxed{}.', 'role': 'system'}
 {'content': 'A committee of 5 is to be chosen from a group of 9 people. How many ways can it be chosen, if Bill and Karl must serve together or not at all, and Alice and Jane refuse to serve with each other?', 'role': 'user'}]
[id]: line_2287
[data_source]: deepscaler-clean-39k_except-still/math-verify
[parsed_output]: {'raw_knowledge': '1. Binomial coefficient formula: The number of ways to choose k items from n distinct items is given by \\(\\binom{n}{k} = \\frac{n!}{k!(n-k)!}\\), used for combinatorial selection.\n2. Case-based decomposition principle: When dealing with constraints like "A and B must be together or not at all," the problem should be split into two separate, mutually exclusive cases (both included or both excluded) to simplify counting.\n3. Subtraction principle for exclusions: If a subset is forbidden (e.g., Alice and Jane cannot both serve), the number of invalid combinations must be subtracted from the total possible combinations in each case to enforce the constraint.\n4. Handling fixed elements in combinations: When certain members are included (e.g., Bill and Karl in Case 1), the combination calculation must adjust by selecting from the remaining pool, and similarly, when forbidden pairs are fixed, the selection focuses on the remaining spots.', 'raw_skeleton': '1. Recognize the constraint that Bill and Karl must both be included or both excluded, leading to two mutually exclusive cases for analysis.\n2. For Case 1 (Bill and Karl both included): Calculate the total number of ways to choose the remaining committee members from the other people, ignoring the Alice-Jane constraint initially.\n3. Within Case 1, identify and subtract the number of invalid committees where Alice and Jane are both selected, as they cannot serve together.\n4. For Case 2 (Bill and Karl both excluded): Calculate the total number of ways to choose the entire committee from the remaining people, again ignoring the Alice-Jane constraint initially.\n5. Within Case 2, identify and subtract the number of invalid committees where Alice and Jane are both selected.\n6. Combine the valid committee counts from both cases to obtain the total number of acceptable committees.', 'raw_solution_breakdown': '1. "If Bill and Karl are on the committee, there are \\(\\binom{7}{3}=35\\) ways for the other group members to be chosen." This calculates the total committees with Bill and Karl included, by choosing 3 from the other 7 people.\n2. "However, if Alice and Jane are on the committee with Bill and Karl, there are \\(\\binom{5}{1}=5\\) ways for the last member to be chosen, yielding 5 unacceptable committees." This identifies and quantifies the invalid committees in this case where Alice and Jane are both present, by fixing Bill, Karl, Alice, and Jane and choosing 1 more from the remaining 5.\n3. "If Bill and Karl are not on the committee, there are \\(\\binom{7}{5}=21\\) ways for the 5 members to be chosen," This computes the total committees without Bill and Karl, by selecting all 5 members from the remaining 7 people.\n4. "but again if Alice and Jane were to be on the committee, there would be \\(\\binom{5}{3}=10\\) ways to choose the other three members, yielding 10 more unacceptable committees." This identifies and quantifies the invalid committees in this case where Alice and Jane are both present, by fixing Alice and Jane and choosing 3 more from the other 5.\n5. "So, we obtain \\((35-5)+(21-10)=41\\) ways the committee can be chosen." This sums the valid committees by subtracting the invalid ones in each case and adding the results.'}
[solution_breakdown_parts]: ['"If Bill and Karl are on the committee, there are \\(\\binom{7}{3}=35\\) ways for the other group members to be chosen." This calculates the total committees with Bill and Karl included, by choosing 3 from the other 7 people.'
 '"However, if Alice and Jane are on the committee with Bill and Karl, there are \\(\\binom{5}{1}=5\\) ways for the last member to be chosen, yielding 5 unacceptable committees." This identifies and quantifies the invalid committees in this case where Alice and Jane are both present, by fixing Bill, Karl, Alice, and Jane and choosing 1 more from the remaining 5.'
 '"If Bill and Karl are not on the committee, there are \\(\\binom{7}{5}=21\\) ways for the 5 members to be chosen," This computes the total committees without Bill and Karl, by selecting all 5 members from the remaining 7 people.'
 '"but again if Alice and Jane were to be on the committee, there would be \\(\\binom{5}{3}=10\\) ways to choose the other three members, yielding 10 more unacceptable committees." This identifies and quantifies the invalid committees in this case where Alice and Jane are both present, by fixing Alice and Jane and choosing 3 more from the other 5. "So, we obtain \\((35-5)+(21-10)=41\\) ways the committee can be chosen." This sums the valid committees by subtracting the invalid ones in each case and adding the results.']
[model_answer]: <PLANNING_SKELETON>
1. Recognize the constraint that Bill and Karl must both be included or both excluded, leading to two mutually exclusive cases for analysis.
2. For Case 1 (Bill and Karl both included): Calculate the total number of ways to choose the remaining committee members from the other people, ignoring the Alice-Jane constraint initially.
3. Within Case 1, identify and subtract the number of invalid committees where Alice and Jane are both selected, as they cannot serve together.
4. For Case 2 (Bill and Karl both excluded): Calculate the total number of ways to choose the entire committee from the remaining people, again ignoring the Alice-Jane constraint initially.
5. Within Case 2, identify and subtract the number of invalid committees where Alice and Jane are both selected.
6. Combine the valid committee counts from both cases to obtain the total number of acceptable committees.
</PLANNING_SKELETON>

<KNOWLEDGE_COMPONENTS>
1. Binomial coefficient formula: The number of ways to choose k items from n distinct items is given by \(\binom{n}{k} = \frac{n!}{k!(n-k)!}\), used for combinatorial selection.
2. Case-based decomposition principle: When dealing with constraints like "A and B must be together or not at all," the problem should be split into two separate, mutually exclusive cases (both included or both excluded) to simplify counting.
3. Subtraction principle for exclusions: If a subset is forbidden (e.g., Alice and Jane cannot both serve), the number of invalid combinations must be subtracted from the total possible combinations in each case to enforce the constraint.
4. Handling fixed elements in combinations: When certain members are included (e.g., Bill and Karl in Case 1), the combination calculation must adjust by selecting from the remaining pool, and similarly, when forbidden pairs are fixed, the selection focuses on the remaining spots.
</KNOWLEDGE_COMPONENTS>

<SOLUTION_BREAKDOWN>
1. "If Bill and Karl are on the committee, there are \(\binom{7}{3}=35\) ways for the other group members to be chosen." This calculates the total committees with Bill and Karl included, by choosing 3 from the other 7 people.
2. "However, if Alice and Jane are on the committee with Bill and Karl, there are \(\binom{5}{1}=5\) ways for the last member to be chosen, yielding 5 unacceptable committees." This identifies and quantifies the invalid committees in this case where Alice and Jane are both present, by fixing Bill, Karl, Alice, and Jane and choosing 1 more from the remaining 5.
3. "If Bill and Karl are not on the committee, there are \(\binom{7}{5}=21\) ways for the 5 members to be chosen," This computes the total committees without Bill and Karl, by selecting all 5 members from the remaining 7 people.
4. "but again if Alice and Jane were to be on the committee, there would be \(\binom{5}{3}=10\) ways to choose the other three members, yielding 10 more unacceptable committees." This identifies and quantifies the invalid committees in this case where Alice and Jane are both present, by fixing Alice and Jane and choosing 3 more from the other 5.
5. "So, we obtain \((35-5)+(21-10)=41\) ways the committee can be chosen." This sums the valid committees by subtracting the invalid ones in each case and adding the results.
</SOLUTION_BREAKDOWN>
[reward_model]: {'ground_truth': '41', 'style': 'rule'}
[knowledge_components_parts]: ['Binomial coefficient formula: The number of ways to choose k items from n distinct items is given by \\(\\binom{n}{k} = \\frac{n!}{k!(n-k)!}\\), used for combinatorial selection.'
 'Case-based decomposition principle: When dealing with constraints like "A and B must be together or not at all," the problem should be split into two separate, mutually exclusive cases (both included or both excluded) to simplify counting.'
 'Subtraction principle for exclusions: If a subset is forbidden (e.g., Alice and Jane cannot both serve), the number of invalid combinations must be subtracted from the total possible combinations in each case to enforce the constraint.'
 'Handling fixed elements in combinations: When certain members are included (e.g., Bill and Karl in Case 1), the combination calculation must adjust by selecting from the remaining pool, and similarly, when forbidden pairs are fixed, the selection focuses on the remaining spots.']
[ability]: math
[planning_skeleton_parts]: ['Recognize the constraint that Bill and Karl must both be included or both excluded, leading to two mutually exclusive cases for analysis.'
 'For Case 1 (Bill and Karl both included): Calculate the total number of ways to choose the remaining committee members from the other people, ignoring the Alice-Jane constraint initially.'
 'Within Case 1, identify and subtract the number of invalid committees where Alice and Jane are both selected, as they cannot serve together. For Case 2 (Bill and Karl both excluded): Calculate the total number of ways to choose the entire committee from the remaining people, again ignoring the Alice-Jane constraint initially.'
 'Within Case 2, identify and subtract the number of invalid committees where Alice and Jane are both selected. Combine the valid committee counts from both cases to obtain the total number of acceptable committees.']
[model_think]: First, I need to understand the problem and the solution. The problem is about selecting a committee of 5 from 9 people with constraints: Bill and Karl must be together or not at all, and Alice and Jane refuse to serve with each other. The solution calculates the number of valid committees by considering cases and subtracting invalid ones.

Now, I have to generate three components with at least four items each: Planning Skeleton, Knowledge Components, and Solution Breakdown.

Starting with the Planning Skeleton. This should be a high-level, ordered list of key reasoning steps without detailed calculations. I need at least four steps.

From the solution, I can infer the logical flow:

1. Consider the case where Bill and Karl are both on the committee.

2. In that case, calculate the number of ways to choose the remaining members, but subtract the cases where Alice and Jane are both included since they can't serve together.

3. Consider the case where Bill and Karl are not on the committee.

4. Calculate the number of ways to choose the committee from the remaining people, again subtracting cases where Alice and Jane are both included.

5. Sum the valid cases from both scenarios.

That gives me five steps, which is more than four, so it should be fine. I need to make them concise and high-level.

Refining:

1. Handle the case where Bill and Karl serve together: Calculate possible committees with them included, minus those where Alice and Jane are both present.

2. Handle the case where Bill and Karl do not serve: Calculate possible committees without them, minus those where Alice and Jane are both present.

3. Combine the results from both cases to get the total number of valid committees.

But that's only three; I need at least four. I should break it down more.

Looking at the solution, it has:

- If Bill and Karl are on: choose 3 from the other 7, but subtract cases where Alice and Jane are both on.

- Specifically, when Bill, Karl, Alice, Jane are all on, choose 1 more from the remaining 5, which is invalid.

Similarly for the other case.

So, for the Planning Skeleton:

1. Case 1: Bill and Karl are both on the committee. Compute the number of ways to choose the remaining 3 members from the other 7 people.

2. Within Case 1, identify and subtract the invalid committees where Alice and Jane are both selected, as they cannot serve together.

3. Case 2: Bill and Karl are not on the committee. Compute the number of ways to choose all 5 members from the remaining 7 people.

4. Within Case 2, identify and subtract the invalid committees where Alice and Jane are both selected.

5. Sum the valid committees from Case 1 and Case 2 to get the total.

That's five steps. I can list them as such.

Now, for Knowledge Components. I need at least four essential facts, definitions, etc.

Relevant knowledge:

- Combinations formula: \binom{n}{k} for choosing k items from n.

- The constraint that Bill and Karl must be together or not at all means we consider two mutually exclusive cases: both in or both out.

- Alice and Jane cannot serve together, so any committee with both is invalid and must be subtracted.

- The total number of people is 9, committee size is 5.

Also, since Bill and Karl are treated as a unit in one case, but in this solution, it's not explicitly a unit; it's handled by fixing them in or out.

More specifically:

1. Formula for combinations: \binom{n}{k} = n! / (k!(n-k)!)

2. Principle of inclusion-exclusion or subtracting invalid cases when dealing with constraints.

3. Definition of mutually exclusive cases: Since Bill and Karl must be together or not, we can split into two scenarios.

4. The condition that Alice and Jane cannot both be on the committee, meaning committees containing both must be excluded.

Also, in the calculation, when Bill and Karl are on, we choose 3 from 7, but if Alice and Jane are both on, we need to find how many such committees.

Similarly for the other case.

I think four should be sufficient. Let me list:

1. Combinatorial selection: The number of ways to choose k items from n is given by the binomial coefficient \binom{n}{k}.

2. Case-based reasoning: When dealing with constraints like "A and B must be together or not at all", it's efficient to consider two separate cases: one where both are included, and one where both are excluded.

3. Subtraction principle: When there are restrictions like "C and D cannot serve together", we calculate the total possible committees and subtract those that violate the restriction.

4. Handling multiple constraints: In this problem, the constraints interact, so we need to apply the subtraction within each case to avoid counting invalid committees.

That seems good.

Now, for Solution Breakdown. I need to divide the ground-truth solution into at least four semantically coherent steps, either direct quotes or faithful summaries.

The solution text is:

"If Bill and Karl are on the committee, there are $\binom{7}{3}=35$ ways for the other group members to be chosen. However, if Alice and Jane are on the committee with Bill and Karl, there are $\binom{5}{1}=5$ ways for the last member to be chosen, yielding 5 unacceptable committees. If Bill and Karl are not on the committee, there are $\binom{7}{5}=21$ ways for the 5 members to be chosen, but again if Alice and Jane were to be on the committee, there would be $\binom{5}{3}=10$ ways to choose the other three members, yielding 10 more unacceptable committees. So, we obtain $(35-5)+(21-10)=41$ ways the committee can be chosen."

I can break this into chunks:

1. Consider the case with Bill and Karl on the committee: There are \binom{7}{3} = 35 ways to choose the other 3 members from the remaining 7 people.

2. But, if Alice and Jane are both included with Bill and Karl, there are \binom{5}{1} = 5 ways to choose the last member (since 4 spots are taken by Bill, Karl, Alice, Jane, and one more from the other 5), which are invalid committees. So, subtract 5 from the 35.

3. Now, consider the case without Bill and Karl: There are \binom{7}{5} = 21 ways to choose 5 members from the remaining 7 people.

4. However, in this case, if Alice and Jane are both on the committee, there are \binom{5}{3} = 10 ways to choose the other 3 members (since Alice and Jane are fixed, choose 3 from the other 5), which are invalid. So, subtract 10 from the 21.

5. Finally, sum the valid committees: (35 - 5) + (21 - 10) = 30 + 11 = 41.

That's five steps. I need at least four, so it's fine. I can present them as numbered items.

For the Solution Breakdown, I should use direct quotes or faithful summaries. Since the solution is concise, I might paraphrase slightly for clarity, but keep it faithful.

In the output format, it says "direct quote or faithful summary", so summaries are okay.

Now, for the Planning Skeleton, I need to ensure it's high-level and not include calculations.

Similarly, Knowledge Components should be general knowledge, not specific to the numbers here.

Finally, output in the specified format.

Let me draft each section.

**Planning Skeleton:**

1. Analyze the constraint for Bill and Karl: They must both be on or both off, leading to two mutually exclusive cases.

2. For Case 1 (Bill and Karl both on): Calculate the number of ways to choose the remaining 3 members from the other 7 people.

3. Subtract the number of invalid committees in Case 1 where Alice and Jane are both selected.

4. For Case 2 (Bill and Karl both off): Calculate the number of ways to choose all 5 members from the remaining 7 people.

5. Subtract the number of invalid committees in Case 2 where Alice and Jane are both selected.

6. Sum the valid committees from both cases for the total.

That's six, but I can combine or adjust to have at least four. Since minimum is four, it's okay to have more.

I could make it:

1. Split into two cases based on Bill and Karl: both included or both excluded.

2. In the inclusion case, compute possible committees and subtract those violating Alice-Jane constraint.

3. In the exclusion case, compute possible committees and subtract those violating Alice-Jane constraint.

4. Combine the results.

But step 2 and 3 might be too broad; I need finer granularity. The instructions say "high degree of granularity" and "if natural has fewer, subdivide".

In the example, they had 5 steps for a simple problem.

So, I'll keep it as above with 5 or 6 steps.

Similarly for others.

**Knowledge Components:**

1. Binomial coefficient: \binom{n}{k} represents the number of ways to choose k items from n distinct items.

2. Principle of case decomposition: When faced with a "must be together or not at all" constraint, divide the problem into two cases: both present or both absent.


In [5]:
# 统计 difficulty_bucket 各类别的数量
counts = df['difficulty_bucket'].value_counts()

print("=== 难度分布统计 (数量) ===")
print(counts)

print("\n=== 难度分布统计 (占比) ===")
print(df['difficulty_bucket'].value_counts(normalize=True) * 100)

=== 难度分布统计 (数量) ===
difficulty_bucket
hard      361
easy      191
medium    189
Name: count, dtype: int64

=== 难度分布统计 (占比) ===
difficulty_bucket
hard      48.717949
easy      25.775978
medium    25.506073
Name: proportion, dtype: float64

In [14]:
parquet_file = pq.ParquetFile(parquet_path)

print(f"行数: {parquet_file.metadata.num_rows}")
print(f"列数: {parquet_file.metadata.num_columns}")
print(f"Row Groups 数量: {parquet_file.num_row_groups}")

print("\n字段结构：")
print(parquet_file.schema_arrow)

行数: 800
列数: 21
Row Groups 数量: 1

字段结构：
data_source: string
prompt: list<element: struct<content: string, role: string>>
  child 0, element: struct<content: string, role: string>
      child 0, content: string
      child 1, role: string
target: list<element: struct<content: string, role: string>>
  child 0, element: struct<content: string, role: string>
      child 0, content: string
      child 1, role: string
ability: string
reward_model: struct<ground_truth: string, style: string>
  child 0, ground_truth: string
  child 1, style: string
extra_info: struct<gt_answer: string, index: int64, question_raw: string, solution_raw: string, source: string, split: string>
  child 0, gt_answer: string
  child 1, index: int64
  child 2, question_raw: string
  child 3, solution_raw: string
  child 4, source: string
  child 5, split: string
difficulty_bucket: string
success_rate_at_k: double
success_count_at_k: int64
qwen_original_row_index: int64
source_row_index: int64
accuracy: double
solution_breakdown_reward: double
-- schema metadata --
pandas: '{"index_columns": [], "column_indexes": [], "columns": [{"name":' + 1729

In [15]:
schema_df = pd.DataFrame([
    {
        "column_name": field.name,
        "arrow_type": str(field.type),
        "nullable": field.nullable,
    }
    for field in parquet_file.schema_arrow
])

display(schema_df)

,column_name,arrow_type,nullable
0,data_source,string,True
1,prompt,"list<element: struct<content: string, role: st...",True
2,target,"list<element: struct<content: string, role: st...",True
3,ability,string,True
4,reward_model,"struct<ground_truth: string, style: string>",True
5,extra_info,"struct<gt_answer: string, index: int64, questi...",True
6,difficulty_bucket,string,True
7,success_rate_at_k,double,True
8,success_count_at_k,int64,True
9,qwen_original_row_index,int64,True
10,source_row_index,int64,True
11,accuracy,double,True
12,solution_breakdown_reward,double,True

openr1原始数据集

In [4]:
parquet_file = pq.ParquetFile(parquet_path)

print(f"行数: {parquet_file.metadata.num_rows}")
print(f"列数: {parquet_file.metadata.num_columns}")
print(f"Row Groups 数量: {parquet_file.num_row_groups}")

print("\n字段结构：")
print(parquet_file.schema_arrow)

行数: 45792
列数: 10
Row Groups 数量: 1

字段结构：
data_source: string
prompt: list<element: struct<content: string, role: string>>
  child 0, element: struct<content: string, role: string>
      child 0, content: string
      child 1, role: string
target: list<element: struct<content: string, role: string>>
  child 0, element: struct<content: string, role: string>
      child 0, content: string
      child 1, role: string
ability: string
reward_model: struct<ground_truth: string, style: string>
  child 0, ground_truth: string
  child 1, style: string
extra_info: struct<index: int64, split: string>
  child 0, index: int64
  child 1, split: string
-- schema metadata --
pandas: '{"index_columns": [{"kind": "range", "name": null, "start": 0, "' + 975

In [5]:
schema_df = pd.DataFrame([
    {
        "column_name": field.name,
        "arrow_type": str(field.type),
        "nullable": field.nullable,
    }
    for field in parquet_file.schema_arrow
])

display(schema_df)

    column_name                                         arrow_type  nullable
0   data_source                                             string      True
1        prompt  list<element: struct<content: string, role: st...      True
2        target  list<element: struct<content: string, role: st...      True
3       ability                                             string      True
4  reward_model        struct<ground_truth: string, style: string>      True
5    extra_info                struct<index: int64, split: string>      True

In [16]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

# —— 新增：打印单条完整示例 ——
print("\n" + "="*30)
print("单条完整数据示例：")
# 读取第一个row group
first_row_group = parquet_file.read_row_group(0)
sample_df = first_row_group.to_pandas().head(1)
print(sample_df)

==============================
单条完整数据示例：
                                     data_source  \
0  deepscaler-clean-39k_except-still/math-verify

                                                                                                                                                                                                                                                                                                                                         prompt  \
0  [{'content': 'Please reason step by step, and put your final answer within \boxed{}.', 'role': 'system'}, {'content': 'A committee of 5 is to be chosen from a group of 9 people. How many ways can it be chosen, if Bill and Karl must serve together or not at all, and Alice and Jane refuse to serve with each other?', 'role': 'user'}]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   target  \
0  [{'content': '"If Bill and Karl are on the committee, there are \(\binom{7}{3}=35\) ways for the other group members to be chosen." This calculates the total committees with Bill and Karl included, by choosing 3 from the other 7 people.

"However, if Alice and Jane are on the committee with Bill and Karl, there are \(\binom{5}{1}=5\) ways for the last member to be chosen, yielding 5 unacceptable committees." This identifies and quantifies the invalid committees in this case where Alice and Jane are both present, by fixing Bill, Karl, Alice, and Jane and choosing 1 more from the remaining 5.

"If Bill and Karl are not on the committee, there are \(\binom{7}{5}=21\) ways for the 5 members to be chosen," This computes the total committees without Bill and Karl, by selecting all 5 members from the remaining 7 people.

"but again if Alice and Jane were to be on the committee, there would be \(\binom{5}{3}=10\) ways to choose the other three members, yielding 10 more unacceptable committees." This identifies and quantifies the invalid committees in this case where Alice and Jane are both present, by fixing Alice and Jane and choosing 3 more from the other 5. "So, we obtain \((35-5)+(21-10)=41\) ways the committee can be chosen." This sums the valid committees by subtracting the invalid ones in each case and adding the results.', 'role': 'assistant'}]

  ability                             reward_model  \
0    math  {'ground_truth': '41', 'style': 'rule'}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     extra_info  \
0  {'gt_answer': '41', 'index': 3830, 'question_raw': 'A committee of 5 is to be chosen from a group of 9 people. How many ways can it be chosen, if Bill and Karl must serve together or not at all, and Alice and Jane refuse to serve with each other?', 'solution_raw': 'If Bill and Karl are on the committee, there are $\binom{7}{3}=35$ ways for the other group members to be chosen. However, if Alice and Jane are on the committee with Bill and Karl, there are $\binom{5}{1}=5$ ways for the last member to be chosen, yielding 5 unacceptable committees. If Bill and Karl are not on the committee, there are $\binom{7}{5}=21$ ways for the 5 members to be chosen, but again if Alice and Jane were to be on the committee, there would be $\binom{5}{3}=10$ ways to choose the other three members, yielding 10 more unacceptable committees. So, we obtain $(35-5)+(21-10)=41$ ways the committee can be chosen.', 'source': 'omni_math', 'split': 'train'}

  difficulty_bucket  success_rate_at_k  success_count_at_k  \
0              hard                0.0                   0

   qwen_original_row_index  source_row_index  accuracy  \
0                     6596              5263       0.0

   solution_breakdown_reward
0                        1.0

In [ ]:
# deepscaler数据集

parquet_file = pq.ParquetFile(parquet_path)

print(f"行数: {parquet_file.metadata.num_rows}")
print(f"列数: {parquet_file.metadata.num_columns}")
print(f"Row Groups 数量: {parquet_file.num_row_groups}")

print("\n字段结构：")
print(parquet_file.schema_arrow)

行数: 800
列数: 33
Row Groups 数量: 1

字段结构：
question: string
solution: string
prompt: list<element: struct<content: string, role: string>>
  child 0, element: struct<content: string, role: string>
      child 0, content: string
      child 1, role: string
id: string
data_source: string
parsed_output: struct<raw_knowledge: string, raw_skeleton: string, raw_solution_breakdown: string>
  child 0, raw_knowledge: string
  child 1, raw_skeleton: string
  child 2, raw_solution_breakdown: string
solution_breakdown_parts: list<element: string>
  child 0, element: string
model_answer: string
reward_model: struct<ground_truth: string, style: string>
  child 0, ground_truth: string
  child 1, style: string
knowledge_components_parts: list<element: string>
  child 0, element: string
ability: string
planning_skeleton_parts: list<element: string>
  child 0, element: string
model_think: string
extra_info: struct<gt_answer: string, index: int64, question_raw: string, solution_raw: string, source: string,  (... 14 chars omitted)
  child 0, gt_answer: string
  child 1, index: int64
  child 2, question_raw: string
  child 3, solution_raw: string
  child 4, source: string
  child 5, split: string
accuracy: double
solution_breakdown_cot_answer: string
solution_breakdown_parts_count: int64
solution_breakdown_reward: double
qwen_original_row_index: int64
source_row_index: int64
difficulty_bucket: string
success_rate_at_k: double
success_count_at_k: int64
rollout_reward_list: list<element: double>
  child 0, element: double
-- schema metadata --
pandas: '{"index_columns": [], "column_indexes": [], "columns": [{"name":' + 3260

In [ ]:
schema_df = pd.DataFrame([
    {
        "column_name": field.name,
        "arrow_type": str(field.type),
        "nullable": field.nullable,
    }
    for field in parquet_file.schema_arrow
])

display(schema_df)